import moment, { Moment } from 'moment';
import { rrulestr, RRuleSet } from 'rrule';
import config from './config';
import {
  CustomSchedulerDate,
  Event,
  EventGroup,
  Resource,
  SchedulerDataConfig,
  SchedulerHeader,
  SlotData,
  SlotDate,
} from './types';
import { ViewTypes, CellUnits } from './enums';
import { DATE_FORMAT, DATETIME_FORMAT } from './constants';
import { isNonWorkingTime } from './_util/isNonWorkingTime';

export interface CustomSchedulerFunc {
  getCustomSchedulerDate?: (data: SchedulerData, num: number, date?: string) => CustomSchedulerDate;
  getSummary?: () => void;
}

export class SchedulerData {
  private cellUnit: number;
  private config: SchedulerDataConfig;
  private customFunc?: CustomSchedulerFunc;
  private documentWidth: number;
  private endDate?: string;
  private eventGroups: EventGroup[];
  private eventGroupsAutoGenerated: boolean;
  private events: Event[];
  private headers: SchedulerHeader[];
  private isEventPerspective: boolean;
  private localeMoment: typeof moment;
  private resizing: boolean;
  private resources: any[];
  private scrollToSpecialMoment: boolean;
  private selectDate?: string;
  private slotData: SlotData[];
  private showAgenda: boolean;
  private startDate?: string;

  /**
   * viewType is the initial view type, now Scheduler supports Day, Week, Month, Quarter, Year
   * 5 built-in view types, in addition Scheduler now supports Custom, Custom1, Custom2 3
   * custom view types at the same time, in which you can control the time window yourself
   */
  private viewType: number;

  constructor(
    date: string = moment().format(DATE_FORMAT),
    viewType = ViewTypes.Week,
    showAgenda = false,
    isEventPerspective = false,
    newConfig?: any,
    customFunc?: CustomSchedulerFunc,
    localeMoment?: typeof moment,
  ) {
    this.resources = [];
    this.events = [];
    this.eventGroups = [];
    this.slotData = [];
    this.eventGroupsAutoGenerated = true;
    this.headers = [];
    this.viewType = viewType;
    this.cellUnit = viewType === ViewTypes.Day ? CellUnits.Hour : CellUnits.Day;
    this.showAgenda = showAgenda;
    this.isEventPerspective = isEventPerspective;
    this.resizing = false;
    this.scrollToSpecialMoment = false;
    this.documentWidth = 0;

    this.localeMoment = moment;
    if (!!localeMoment) {
      this.localeMoment = localeMoment;
    }

    this.config = !newConfig ? config : { ...config, ...newConfig };
    this.validateMinuteStep(this.config.minuteStep);
    this.customFunc = customFunc;
    this.resolveDateRange(0, date);
    this.createHeaders();
    this.createSlotData();
  }

  public setEvents(events: Event[]) {
    this.validateEvents(events);
    this.events = events;

    if (this.eventGroupsAutoGenerated) {
      this.generateEventGroups();
    }

    if (this.config.recurringEventsEnabled) {
      this.handleRecurringEvents();
    }

    this.createSlotData();
  }

  public setResources(resources: Resource[]) {
    this.validateResource(resources);
    this.resources = resources;
    this.createSlotData();
    // this.setScrollToSpecialMoment(true);
  }

  // =============================================================================
  // PRIVATE METHODS
  // =============================================================================

  /**
   * Attach an event into the event array at the specific position.
   * @param event An event object.
   */
  private attachEvent(event: Event) {
    let pos = 0;
    const eventStart = this.localeMoment(event.start);
    this.events.forEach((evt, index) => {
      const start = this.localeMoment(evt.start);
      if (eventStart >= start) {
        pos = index + 1;
      }
    });
    this.events.splice(pos, 0, event);
  }

  private createHeaders() {
    this.headers = [];
    let start = this.localeMoment(this.startDate);
    let end = this.localeMoment(this.endDate);
    let header = start;

    if (this.showAgenda) {
      this.headers.push({ time: header.format(DATETIME_FORMAT), nonWorkingTime: false });
    } else {
      if (this.cellUnit === CellUnits.Hour) {
        start = start.add(this.config.dayStartFrom, 'hours');
        end = end.add(this.config.dayStopTo, 'hours');
        header = start;

        while (header >= start && header <= end) {
          const minuteSteps = this.getMinuteStepsInHour();
          for (let i = 0; i < minuteSteps; i++) {
            const hour = header.hour();
            if (
              this.config.dayStartFrom &&
              this.config.dayStopTo &&
              hour >= this.config.dayStartFrom &&
              hour <= this.config.dayStopTo
            ) {
              const time = header.format(DATETIME_FORMAT);
              const nonWorkingTime = isNonWorkingTime(this, time);
              this.headers.push({ time, nonWorkingTime });
            }

            header = header.add(this.config.minuteStep, 'minutes');
          }
        }
      } else {
        while (header >= start && header <= end) {
          const time = header.format(DATETIME_FORMAT);
          const dayOfWeek = header.weekday();
          if (this.config.displayWeekend || (dayOfWeek !== 0 && dayOfWeek !== 6)) {
            const nonWorkingTime = isNonWorkingTime(this, time);
            this.headers.push({ time, nonWorkingTime });
          }

          header = header.add(1, 'days');
        }
      }
    }
  }

  private createSlotData() {
    // Initial render data
    this.slotData = this.initializeSlotData(
      this.isEventPerspective,
      this.eventGroups,
      this.resources,
      this.headers,
    );
    const cellMaxEventsCount = this.getCellMaxEvents();
    const cellMaxEventsCountValue = 30;

    // Loop throught events.
    this.events.forEach(event => {
      const slots = this.slotData.filter(s => s.id.toString() === this.getEventSlotId(event));

      if (slots.length > 0) {
        const slot = slots[0];
        const span = this.getSpan(event.start, event.end);
        const eventStart = this.localeMoment(event.start);
        const eventEnd = this.localeMoment(event.end);
        let indx = -1;

        slot.dates.forEach((slotDate, index) => {
          const slotDateStart = this.localeMoment(slotDate.start);
          const slotDateEnd = this.localeMoment(slotDate.end);

          if (slotDateEnd > eventStart && slotDateStart < eventEnd) {
            slotDate.count = (slotDate.count || 0) + 1;
            if (slotDate.count > slot.rowMaxCount) {
              slot.rowMaxCount = slotDate.count;
              const rowsCount =
                cellMaxEventsCount <= cellMaxEventsCountValue &&
                slot.rowMaxCount > cellMaxEventsCount
                  ? cellMaxEventsCount
                  : slot.rowMaxCount;
              const newRowHeight =
                rowsCount * this.config.eventItemLineHeight +
                (this.config.creatable && this.config.checkConflict === false ? 20 : 2);
              if (newRowHeight > slot.rowHeight) {
                slot.rowHeight = newRowHeight;
              }
            }

            if (indx === -1) {
              let tmp = 0;
              if (slotDate.events) {
                while (slotDate.events[tmp] !== undefined) {
                  tmp++;
                }
              }

              indx = tmp;
            }

            let render = slotDateStart <= eventStart || index === 0;
            if (render === false) {
              const previousHeader = slot.dates[index - 1];
              const previousHeaderStart = this.localeMoment(previousHeader.start);
              const previousHeaderEnd = this.localeMoment(previousHeader.end);
              if (previousHeaderEnd <= eventStart || previousHeaderStart >= eventEnd) {
                render = true;
              }
            }

            if (slotDate.events) {
              // slotDate.events[indx] = this.createSlotDate(render, span, event);
            }
          }
        });
      }
    });

    if (
      cellMaxEventsCount <=
      cellMaxEventsCountValue /*||
      this.customFunc && this.customFunc.getSummaryFunc !== undefined*/
    ) {
      this.slotData.forEach(slot => {
        const hasSummary = false;

        slot.dates.forEach(slotDate => {
          if (cellMaxEventsCount <= cellMaxEventsCountValue) {
            let renderItemsCount = 0;
            let addMoreIndex = 0;
            let index = 0;
            while (index < cellMaxEventsCount - 1) {
              if (slotDate.events[index] !== undefined) {
                renderItemsCount++;
                addMoreIndex = index + 1;
              }

              index++;
            }

            if (slotDate.events[index] !== undefined) {
              if (renderItemsCount + 1 < slotDate.count) {
                slotDate.addMore = slotDate.count - renderItemsCount;
                slotDate.addMoreIndex = addMoreIndex;
              }
            } else {
              if (renderItemsCount < slotDate.count) {
                slotDate.addMore = slotDate.count - renderItemsCount;
                slotDate.addMoreIndex = addMoreIndex;
              }
            }
          }

          if (this.customFunc && this.customFunc.getSummary) {
            /* const events: Event[] = [];
            slotDate.events.forEach(event => {
              if (!!event && !!event.eventItem) {
                events.push(event.eventItem);
              }
            });

            if (this.customFunc && this.customFunc.getSummary) {
              slotDate.summary = this.customFunc.getSummary(
                this,
                events,
                resourceEvents.id,
                resourceEvents.name,
                slotDate.start,
                slotDate.end,
              );
            }
            
            if (!!slotDate.summary && slotDate.summary.text) {
              hasSummary = true;
            } */
          }
        });

        slot.hasSummary = hasSummary;
        if (hasSummary) {
          const rowsCount =
            cellMaxEventsCount <= cellMaxEventsCountValue && slot.rowMaxCount > cellMaxEventsCount
              ? cellMaxEventsCount
              : slot.rowMaxCount;
          const newRowHeight =
            (rowsCount + 1) * this.config.eventItemLineHeight +
            (this.config.creatable && this.config.checkConflict === false ? 20 : 2);
          if (newRowHeight > slot.rowHeight) {
            slot.rowHeight = newRowHeight;
          }
        }
      });
    }
  }

  private createSlotDate(render: any, span: any, event: Event) {
    return {
      render,
      span,
      event,
    };
  }

  private detachEvent(event: Event) {
    const index = this.events.indexOf(event);
    if (index !== -1) {
      this.events.splice(index, 1);
    }
  }

  private generateEventGroups() {
    this.eventGroups = [];
    const set = new Set();
    this.events.forEach(event => {
      const id = this.getEventGroupId(event);
      const name = this.getEventGroupName(event);

      if (!set.has(id)) {
        this.eventGroups.push({
          id,
          name,
          event,
        });

        set.add(id);
      }
    });
  }

  private getCellMaxEvents() {
    return this.viewType === ViewTypes.Week
      ? this.config.weekMaxEvents
      : this.viewType === ViewTypes.Day
      ? this.config.dayMaxEvents
      : this.viewType === ViewTypes.Month
      ? this.config.monthMaxEvents
      : this.viewType === ViewTypes.Year
      ? this.config.yearMaxEvents
      : this.viewType === ViewTypes.Quarter
      ? this.config.quarterMaxEvents
      : this.config.customMaxEvents;
  }

  private getEventSlotId(event: Event) {
    return this.isEventPerspective ? this.getEventGroupId(event) : event.resourceId;
  }

  private getEventGroupId(event: Event) {
    return !!event.groupId ? event.groupId.toString() : event.id.toString();
  }

  private getEventGroupName(event: Event) {
    return !!event.groupName ? event.groupName : event.title;
  }

  private getMinuteStepsInHour() {
    return 60 / this.config.minuteStep;
  }

  private getSpan(startTime: string, endTime: string) {
    if (this.showAgenda) {
      return 1;
    }

    const start = this.localeMoment(startTime);
    const end = this.localeMoment(endTime);
    let span = 0;

    for (const header of this.headers) {
      const spanStart = this.localeMoment(header.time);
      const spanEnd =
        this.cellUnit === CellUnits.Hour
          ? this.localeMoment(header.time).add(this.config.minuteStep, 'minutes')
          : this.localeMoment(header.time).add(1, 'days');

      if (spanStart < end && spanEnd > start) {
        span++;
      }
    }

    return span;
  }

  private handleRecurringEvents() {
    const recurringEvents = this.events.filter(x => !!x.rrule);
    recurringEvents.forEach(event => {
      this.detachEvent(event);
    });

    recurringEvents.forEach(event => {
      const windowStart = this.localeMoment(this.startDate);
      const windowEnd = this.localeMoment(this.endDate).add(1, 'days');
      const eventStart = this.localeMoment(event.start);
      const eventEnd = this.localeMoment(event.end);
      let rule = rrulestr(event.rrule || '');
      const oldDtstart = !!rule.origOptions.dtstart
        ? this.localeMoment(rule.origOptions.dtstart)
        : undefined;

      if (!rule.origOptions.until || windowEnd < this.localeMoment(rule.origOptions.until)) {
        rule.origOptions.until = windowEnd.toDate();
      }

      // reload
      rule = rrulestr(rule.toString());
      /* if (event.exdates || event.exrule) {
        const rruleSet = new RRuleSet();
        rruleSet.rrule(rule);
        if (event.exrule) {
          rruleSet.exrule(rrulestr(event.exrule));
        }
        if (event.exdates) {
          event.exdates.forEach(exdate => {
            rruleSet.exdate(this.localeMoment(exdate).toDate());
          });
        }
        rule = rruleSet;
      } */

      const all = rule.all();
      const newEvents: Event[] = all.map((time, index) => {
        return {
          ...event,
          recurringEventId: event.id,
          recurringEventStart: event.start,
          recurringEventEnd: event.end,
          id: `${event.id}-${index}`,
          start: rule.origOptions.tzid
            ? this.localeMoment
                .utc(time)
                .utcOffset(this.localeMoment().utcOffset(), true)
                .format(DATETIME_FORMAT)
            : this.localeMoment(time).format(DATETIME_FORMAT),
          end: rule.origOptions.tzid
            ? this.localeMoment
                .utc(time)
                .utcOffset(this.localeMoment().utcOffset(), true)
                .add(eventEnd.diff(eventStart), 'ms')
                .format(DATETIME_FORMAT)
            : this.localeMoment(time)
                .add(eventEnd.diff(eventStart), 'ms')
                .format(DATETIME_FORMAT),
        };
      });

      newEvents.forEach(newEvent => {
        const newEventStart = this.localeMoment(newEvent.start);
        const newEventEnd = this.localeMoment(newEvent.end);

        if (
          newEventStart < windowEnd &&
          newEventEnd > windowStart &&
          (!oldDtstart || newEventStart >= oldDtstart)
        ) {
          this.attachEvent(newEvent);
        }
      });
    });
  }

  private initializeSlotDates(header: SchedulerHeader) {
    const startDt = this.localeMoment(header.time);
    const start = startDt.format(DATETIME_FORMAT);
    const end = this.showAgenda
      ? this.viewType === ViewTypes.Week
        ? startDt.add(1, 'weeks').format(DATETIME_FORMAT)
        : this.viewType === ViewTypes.Day
        ? startDt.add(1, 'days').format(DATETIME_FORMAT)
        : this.viewType === ViewTypes.Month
        ? startDt.add(1, 'months').format(DATETIME_FORMAT)
        : this.viewType === ViewTypes.Year
        ? startDt.add(1, 'years').format(DATETIME_FORMAT)
        : this.viewType === ViewTypes.Quarter
        ? startDt.add(1, 'quarters').format(DATETIME_FORMAT)
        : this.localeMoment(this.endDate)
            .add(1, 'days')
            .format(DATETIME_FORMAT)
      : this.cellUnit === CellUnits.Hour
      ? startDt.add(this.config.minuteStep, 'minutes').format(DATETIME_FORMAT)
      : startDt.add(1, 'days').format(DATETIME_FORMAT);

    return {
      time: header.time,
      nonWorkingTime: header.nonWorkingTime,
      start,
      end,
      count: 0,
      addMore: 0,
      addMoreIndex: 0,
      events: [], // [, , ,],
    } as SlotDate;
  }

  private initializeSlotData(
    isEventPerspective: boolean,
    eventGroups: any[],
    resources: any[],
    headers: SchedulerHeader[],
  ) {
    const slots = isEventPerspective ? eventGroups : resources;
    const slotTree: any[] = [];
    const slotMap = new Map();

    // Loop through each resource.
    slots.forEach(slot => {
      const dates = headers.map(header => {
        return this.initializeSlotDates(header);
      });

      const data: SlotData = {
        id: slot.id,
        name: slot.name,
        parentId: slot.parentId,
        groupOnly: slot.groupOnly,
        hasSummary: false,
        rowMaxCount: 0,
        rowHeight:
          this.config.nonAgendaSlotMinHeight !== 0
            ? this.config.nonAgendaSlotMinHeight
            : this.config.eventItemLineHeight + 2,
        dates,
        indent: 0,
        hasChildren: false,
        expanded: true,
        render: true,
      };
      let value;

      if (slotMap.has(slot.id)) {
        value = slotMap.get(slot.id);
        value.data = data;
      } else {
        value = {
          data,
          children: [],
        };
        slotMap.set(slot.id, value);
      }

      const parentId = slot.parentId;
      if (!parentId || parentId === slot.id) {
        slotTree.push(value);
      } else {
        let parentValue;
        if (slotMap.has(parentId)) {
          parentValue = slotMap.get(parentId);
        } else {
          parentValue = {
            data: undefined,
            children: [],
          };
          slotMap.set(parentId, parentValue);
        }

        parentValue.children.push(value);
      }
    });

    const slotStack = [];
    let i;
    for (i = slotTree.length - 1; i >= 0; i--) {
      slotStack.push(slotTree[i]);
    }

    const initialData: SlotData[] = [];
    let currentNode;
    while (slotStack.length > 0) {
      currentNode = slotStack.pop();
      if (currentNode.data.indent > 0) {
        currentNode.data.render = this.config.defaultExpanded;
      }
      if (currentNode.children.length > 0) {
        currentNode.data.hasChildren = true;
        currentNode.data.expanded = this.config.defaultExpanded;
      }
      initialData.push(currentNode.data);

      for (i = currentNode.children.length - 1; i >= 0; i--) {
        currentNode.children[i].data.indent = currentNode.data.indent + 1;
        slotStack.push(currentNode.children[i]);
      }
    }

    return initialData;
  }

  private resolveDateRange(num: number, date?: string) {
    if (date) {
      this.selectDate = this.localeMoment(date).format(DATE_FORMAT);
    }

    if (this.viewType === ViewTypes.Week) {
      this.startDate = date
        ? this.localeMoment(date)
            .startOf('week')
            .format(DATE_FORMAT)
        : this.localeMoment(this.startDate)
            .add(num, 'weeks')
            .format(DATE_FORMAT);
      this.endDate = this.localeMoment(this.startDate)
        .endOf('week')
        .format(DATE_FORMAT);
    } else if (this.viewType === ViewTypes.Day) {
      this.startDate = date
        ? this.selectDate
        : this.localeMoment(this.startDate)
            .add(num, 'days')
            .format(DATE_FORMAT);
      this.endDate = this.startDate;
    } else if (this.viewType === ViewTypes.Month) {
      this.startDate = date
        ? this.localeMoment(date)
            .startOf('month')
            .format(DATE_FORMAT)
        : this.localeMoment(this.startDate)
            .add(num, 'months')
            .format(DATE_FORMAT);
      this.endDate = this.localeMoment(this.startDate)
        .endOf('month')
        .format(DATE_FORMAT);
    } else if (this.viewType === ViewTypes.Quarter) {
      this.startDate = date
        ? this.localeMoment(date)
            .startOf('quarter')
            .format(DATE_FORMAT)
        : this.localeMoment(this.startDate)
            .add(num, 'quarters')
            .format(DATE_FORMAT);
      this.endDate = this.localeMoment(this.startDate)
        .endOf('quarter')
        .format(DATE_FORMAT);
    } else if (this.viewType === ViewTypes.Year) {
      this.startDate = date
        ? this.localeMoment(date)
            .startOf('year')
            .format(DATE_FORMAT)
        : this.localeMoment(this.startDate)
            .add(num, 'years')
            .format(DATE_FORMAT);
      this.endDate = this.localeMoment(this.startDate)
        .endOf('year')
        .format(DATE_FORMAT);
    } else if (
      this.viewType === ViewTypes.Custom ||
      this.viewType === ViewTypes.Custom1 ||
      this.viewType === ViewTypes.Custom2
    ) {
      if (this.customFunc && this.customFunc.getCustomSchedulerDate) {
        const customDate = this.customFunc.getCustomSchedulerDate(this, num, date);
        this.startDate = customDate.startDate;
        this.endDate = customDate.endDate;
        if (!!customDate.cellUnit) {
          this.cellUnit = customDate.cellUnit;
        }
      } else {
        throw new Error(
          'This is custom view type, set behaviors.getCustomSchedulerDateFunc func to resolve the time window(startDate and endDate) yourself',
        );
      }
    }
  }

  private validateEvents(events: Event[]) {
    if (Object.prototype.toString.call(events) !== '[object Array]') {
      throw new Error('Events should be Array object');
    }

    events.forEach((evt, index) => {
      if (!evt) {
        console.error(`Event undefined: ${index}`);
        throw new Error(`Event undefined: ${index}`);
      }

      if (!evt.id || !evt.resourceId || !evt.title || !evt.start || !evt.end) {
        console.error('Event property missed', index, evt);
        throw new Error(`Event property undefined: ${index}`);
      }
    });
  }

  private validateMinuteStep(minuteStep: number) {
    if (60 % minuteStep !== 0) {
      console.error(
        'Minute step is not set properly - 60 minutes must be divisible without remainder by this number',
      );
      throw new Error(
        'Minute step is not set properly - 60 minutes must be divisible without remainder by this number',
      );
    }
  }

  private validateResource(resources: Resource[]) {
    if (Object.prototype.toString.call(resources) !== '[object Array]') {
      throw new Error('Resources should be Array object');
    }

    resources.forEach((r, index) => {
      if (!r) {
        console.error(`Resource undefined: ${index}`);
        throw new Error(`Resource undefined: ${index}`);
      }
      if (!r.id || !r.name) {
        console.error('Resource property missed', index, r);
        throw new Error(`Resource property undefined: ${index}`);
      }
    });
  }
}
